import {useState} from "react";
import type {AnswerCitation} from "../types";
import {RagApi} from "../api";
type Props={api:RagApi;onBack:()=>void;onSources:()=>void;onLogout:()=>void};
export function ChatPage({api,onBack,onSources,onLogout}:Props){
 const[messages,setMessages]=useState<{role:"user"|"assistant";content:string;citations?:AnswerCitation[]}[]>([]);
 const[question,setQuestion]=useState("");const[conversationId,setConversationId]=useState<string>();const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[traceId,setTraceId]=useState("");
 async function submit(){const text=question.trim();if(!text||loading)return;setQuestion("");setError("");setMessages(p=>[...p,{role:"user",content:text},{role:"assistant",content:""}]);setLoading(true);let answer="";let citations:AnswerCitation[]=[];
 try{for await(const event of api.streamAnswer(text,conversationId)){if(event.type==="delta"){answer+=event.content;setMessages(p=>{const n=[...p];n[n.length-1]={role:"assistant",content:answer,citations};return n;});}else if(event.type==="done"){setConversationId(event.conversation_id);citations=event.citations;if(event.trace_id)setTraceId(event.trace_id);setMessages(p=>{const n=[...p];n[n.length-1]={role:"assistant",content:answer,citations};return n;});}else throw new Error(event.detail);}}
 catch(e){setError(e instanceof Error?e.message:"Chat failed");setMessages(p=>p[p.length-1]?.content?p:p.slice(0,-1));}finally{setLoading(false);}}
 return <div className="app-shell"><header className="topbar"><div><strong>Private Knowledge</strong><span>Chat</span></div><nav><button className="ghost" onClick={onSources}>Sources</button><button className="ghost" onClick={onBack}>Search</button><button className="ghost" onClick={onLogout}>Sign out</button></nav></header><main className="content narrow"><div className="page-title"><p className="eyebrow">GROUNDED CHAT</p><h1>Ask your knowledge base</h1><p>Answers are generated from retrieved evidence and show supporting sources.</p></div><section className="chat-thread">{messages.length===0&&<div className="empty"><div className="empty-icon">✦</div><h3>Start a conversation</h3><p>Ask about your indexed emails and documents.</p></div>}{messages.map((m,i)=><article className={`chat-message ${m.role}`} key={i}><div className="chat-role">{m.role==="user"?"You":"Assistant"}</div><div className="chat-body">{m.content||<span className="typing">Thinking…</span>}</div>{m.role==="assistant"&&m.citations?.length&&<div className="citation-list"><div className="citation-title">Sources</div>{m.citations.map(c=><div className="citation-card" key={c.id}><strong>[{c.id}] {c.source_name}</strong><span>{c.text}</span><small>Chunk {c.chunk_id}</small></div>)}</div>}</article>)}</section>{error&&<div className="error banner">{error}</div>}<div className="chat-composer"><textarea aria-label="Chat message" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void submit();}}} placeholder="Ask a question…"/><button onClick={()=>void submit()} disabled={loading||!question.trim()}>{loading?"Generating…":"Send"}</button></div></main></div>;
}